/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BCardImg: typeof import('bootstrap-vue-next/components/BCard')['BCardImg']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BDatePicker: typeof import('bootstrap-vue-next/components/BDatePicker')['BDatePicker']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormDatepicker: typeof import('bootstrap-vue-next/components/BFormDatepicker')['BFormDatepicker']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BImg: typeof import('bootstrap-vue-next/components/BImg')['BImg']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BLink: typeof import('bootstrap-vue-next/components/BLink')['BLink']
    BListGroup: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroupItem']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BPagination: typeof import('bootstrap-vue-next/components/BPagination')['BPagination']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BTable: typeof import('bootstrap-vue-next/components/BTable')['BTable']
    Cardinfo: typeof import('./src/components/Cardinfo.vue')['default']
    CardInfo: typeof import('./src/components/CardInfo.vue')['default']
    Grafic: typeof import('./src/components/Grafic.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    ProductTable: typeof import('./src/components/ProductTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shipments_component: typeof import('./src/components/Shipments_component.vue')['default']
    ShipmentsComponent: typeof import('./src/components/ShipmentsComponent.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Users_component: typeof import('./src/components/Users_component.vue')['default']
    UsersComponent: typeof import('./src/components/UsersComponent.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
