version: '3.8'

services:
  web:
    build:
      context: ./my-site
      dockerfile: Dockerfile
    ports:
      - "8007:80" # Exponer el puerto 80 de nginx en el puerto 8007 de tu host hola
    volumes:
      - ./my-site/nginx.conf:/etc/nginx/nginx.conf # Ruta corregida
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

    #Prueba
